#include "Edge.h"
#include "FloatImage.h"
#include "GLine2D.h"
//#include "GLineSegment2D.h"
#include "Gaussian.h"
//#include "GrayModel.h"
//#include "Gridder.h"
#include "Homography33.h"
#include "MathUtil.h"
//#include "Quad.h"
//#include "Segment.h"
//#include "TagDetection.h"
//#include "TagDetector.h"
//#include "TagFamily.h"
#include "UnionFindSimple.h"
#include "XYWeight.h"

